package com.joole.domain;
// Generated Nov 20, 2019 3:12:05 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Manufacturer generated by hbm2java
 */
@Entity
@Table(name = "Manufacturer", schema = "dbo", catalog = "joole")
public class Manufacturer implements java.io.Serializable {

	private int id;
	private String name;
	private String department;
	private String phone;
	private String email;
	private String web;
	private Set<Product> products = new HashSet<Product>(0);

	public Manufacturer() {
	}

	public Manufacturer(String name, String department, String phone, String email, String web, Set<Product> products) {
		this.name = name;
		this.department = department;
		this.phone = phone;
		this.email = email;
		this.web = web;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "department", length = 45)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "web", length = 45)
	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "manufacturer")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
