package com.joole.domain;
// Generated Nov 20, 2019 3:12:05 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product", schema = "dbo", catalog = "joole")
public class Product implements java.io.Serializable {

	private int id;
	private Manufacturer manufacturer;
	private String picture;
	private String series;
	private String model;
	private String type;
	private String useType;
	private String application;
	private String mounting;
	private String accessories;
	private Integer year;
	private Integer airflow;
	private Double maxPower;
	private Double minPower;
	private Integer maxVoltage;
	private Integer minVoltage;
	private Integer maxSpeed;
	private Integer minSpeed;
	private Integer numberFanSpeed;
	private Integer sound;
	private Integer fanSweep;
	private Double maxHeight;
	private Double minHeight;
	private Double weight;
	private Integer firm;
	private Integer global;
	private String details;

	public Product() {
	}

	public Product(Manufacturer manufacturer, String picture, String series, String model, String type, String useType,
			String application, String mounting, String accessories, Integer year, Integer airflow, Double maxPower,
			Double minPower, Integer maxVoltage, Integer minVoltage, Integer maxSpeed, Integer minSpeed,
			Integer numberFanSpeed, Integer sound, Integer fanSweep, Double maxHeight, Double minHeight, Double weight,
			Integer firm, Integer global, String details) {
		this.manufacturer = manufacturer;
		this.picture = picture;
		this.series = series;
		this.model = model;
		this.type = type;
		this.useType = useType;
		this.application = application;
		this.mounting = mounting;
		this.accessories = accessories;
		this.year = year;
		this.airflow = airflow;
		this.maxPower = maxPower;
		this.minPower = minPower;
		this.maxVoltage = maxVoltage;
		this.minVoltage = minVoltage;
		this.maxSpeed = maxSpeed;
		this.minSpeed = minSpeed;
		this.numberFanSpeed = numberFanSpeed;
		this.sound = sound;
		this.fanSweep = fanSweep;
		this.maxHeight = maxHeight;
		this.minHeight = minHeight;
		this.weight = weight;
		this.firm = firm;
		this.global = global;
		this.details = details;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "manufacturer")
	public Manufacturer getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(Manufacturer manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "picture", length = 100)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "series", length = 45)
	public String getSeries() {
		return this.series;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	@Column(name = "model", length = 45)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "use_type", length = 45)
	public String getUseType() {
		return this.useType;
	}

	public void setUseType(String useType) {
		this.useType = useType;
	}

	@Column(name = "application", length = 45)
	public String getApplication() {
		return this.application;
	}

	public void setApplication(String application) {
		this.application = application;
	}

	@Column(name = "mounting", length = 45)
	public String getMounting() {
		return this.mounting;
	}

	public void setMounting(String mounting) {
		this.mounting = mounting;
	}

	@Column(name = "accessories", length = 45)
	public String getAccessories() {
		return this.accessories;
	}

	public void setAccessories(String accessories) {
		this.accessories = accessories;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "airflow")
	public Integer getAirflow() {
		return this.airflow;
	}

	public void setAirflow(Integer airflow) {
		this.airflow = airflow;
	}

	@Column(name = "max_power", precision = 53, scale = 0)
	public Double getMaxPower() {
		return this.maxPower;
	}

	public void setMaxPower(Double maxPower) {
		this.maxPower = maxPower;
	}

	@Column(name = "min_power", precision = 53, scale = 0)
	public Double getMinPower() {
		return this.minPower;
	}

	public void setMinPower(Double minPower) {
		this.minPower = minPower;
	}

	@Column(name = "max_voltage")
	public Integer getMaxVoltage() {
		return this.maxVoltage;
	}

	public void setMaxVoltage(Integer maxVoltage) {
		this.maxVoltage = maxVoltage;
	}

	@Column(name = "min_voltage")
	public Integer getMinVoltage() {
		return this.minVoltage;
	}

	public void setMinVoltage(Integer minVoltage) {
		this.minVoltage = minVoltage;
	}

	@Column(name = "max_speed")
	public Integer getMaxSpeed() {
		return this.maxSpeed;
	}

	public void setMaxSpeed(Integer maxSpeed) {
		this.maxSpeed = maxSpeed;
	}

	@Column(name = "min_speed")
	public Integer getMinSpeed() {
		return this.minSpeed;
	}

	public void setMinSpeed(Integer minSpeed) {
		this.minSpeed = minSpeed;
	}

	@Column(name = "number_fan_speed")
	public Integer getNumberFanSpeed() {
		return this.numberFanSpeed;
	}

	public void setNumberFanSpeed(Integer numberFanSpeed) {
		this.numberFanSpeed = numberFanSpeed;
	}

	@Column(name = "sound")
	public Integer getSound() {
		return this.sound;
	}

	public void setSound(Integer sound) {
		this.sound = sound;
	}

	@Column(name = "fan_sweep")
	public Integer getFanSweep() {
		return this.fanSweep;
	}

	public void setFanSweep(Integer fanSweep) {
		this.fanSweep = fanSweep;
	}

	@Column(name = "max_height", precision = 53, scale = 0)
	public Double getMaxHeight() {
		return this.maxHeight;
	}

	public void setMaxHeight(Double maxHeight) {
		this.maxHeight = maxHeight;
	}

	@Column(name = "min_height", precision = 53, scale = 0)
	public Double getMinHeight() {
		return this.minHeight;
	}

	public void setMinHeight(Double minHeight) {
		this.minHeight = minHeight;
	}

	@Column(name = "weight", precision = 53, scale = 0)
	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	@Column(name = "firm")
	public Integer getFirm() {
		return this.firm;
	}

	public void setFirm(Integer firm) {
		this.firm = firm;
	}

	@Column(name = "global")
	public Integer getGlobal() {
		return this.global;
	}

	public void setGlobal(Integer global) {
		this.global = global;
	}

	@Column(name = "details", length = 500)
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

}
